Node v14 changes
entrinsik-org/hapi-sequelize pull request #36
Opened 2021-01-18 18:06 UTC by derek-oneill

2021-01-18 19:33 UTC, derek-oneill commented
associated PR https://github.com/entrinsik-org/i5/pull/4636

2021-02-18 21:35 UTC, gmsewell6 requested changes

2021-02-18 21:35 UTC, gmsewell6 commented on package.json
> +        "sequelize": "6.3.5",
this must be changed back for testing if now using the internal fork that is based on the v3 base branch and this lib must be ensured compatible with the internal fork

marking this so the pr is not merged too early by accident.

2021-06-14 14:19 UTC, gmsewell6 requested changes
marking for changes once sequelize fork is namespaced

2021-06-14 19:49 UTC, gmsewell6 requested changes
marking for changes once sequelize fork is namespaced

2021-06-14 19:49 UTC, gmsewell6 commented on package.json
> +        "@entrinsik/informer-sequelize": "~3.35.1",
allow npm to re-order the package.json file then re-commit. Otherwise every npm install for this lib will re-order package.json b/c this dependency is now sorted by `@` instead of `s` which is a big nuisance

2021-06-14 19:49 UTC, gmsewell6 commented on package.json
> +    "version": "8.0.0",
don't worry about this yet. Will do the version bump & publish as part of the normal release process upon final approval

2021-06-14 19:49 UTC, gmsewell6 commented on package.json
> +        "pg": "^8.0.0",
any particular reason for not maintaining consistency using the same version ref `~8.5.1` that we reference in the newly forked private sequelize?

2021-06-24 12:31 UTC, bleupen requested changes

2021-06-24 12:31 UTC, bleupen commented on package.json
> +        "pg": "~8.5.1",
pg is up to 8.6 now. should we go with that?

2021-06-24 17:52 UTC, merged